# mamba env update -n $(basename $PWD) -f conda.yml
channels:
  - conda-forge
  - defaults
dependencies:
  - sysroot_linux-64 2.34
  - cxx-compiler
  - ccache
  - pkg-config
  - libtool
  - autoconf
  - automake
  - cmake
  - make
  - ninja
  - gdb
  - gtest
# libs
  - boost
  - openssl
  - cppzmq
